export enum UserActionTypes {
  SET_USER_TOKEN = '@@user/SET_USER_TOKEN',
  SET_RESERVE_PRAYING_TIME = '@@user/SET_RESERVE_PRAYING_TIME',

  SET_USER_PROFILE_REQUEST = '@@user/SET_USER_PROFILE_REQUEST',
  SET_USER_PROFILE_SUCCESS = '@@user/SET_USER_PROFILE_SUCCESS',
  SET_USER_PROFILE_FAILURE = '@@user/SET_USER_PROFILE_FAILURE',
  SET_USER_PROFILE_CANCEL = '@@user/SET_USER_PROFILE_CANCEL',

  UPDATE_USER_PROFILE_REQUEST = '@@user/UPDATE_USER_PROFILE_REQUEST',
  UPDATE_USER_PROFILE_SUCCESS = '@@user/UPDATE_USER_PROFILE_SUCCESS',
  UPDATE_USER_PROFILE_FAILURE = '@@user/UPDATE_USER_PROFILE_FAILURE',
  UPDATE_USER_PROFILE_CANCEL = '@@user/UPDATE_USER_PROFILE_CANCEL',

  DELETE_USER_PROFILE_REQUEST = '@@user/DELETE_USER_PROFILE_REQUEST',
  DELETE_USER_PROFILE_SUCCESS = '@@user/DELETE_USER_PROFILE_SUCCESS',
  DELETE_USER_PROFILE_FAILURE = '@@user/DELETE_USER_PROFILE_FAILURE',
  DELETE_USER_PROFILE_CANCEL = '@@user/DELETE_USER_PROFILE_CANCEL',

  CANCEL_PRAYING_RESERVATION_REQUEST = '@@user/CANCEL_PRAYING_RESERVATION_REQUEST',
  CANCEL_PRAYING_RESERVATION_SUCCESS = '@@user/CANCEL_PRAYING_RESERVATION_SUCCESS',
  CANCEL_PRAYING_RESERVATION_FAILURE = '@@user/CANCEL_PRAYING_RESERVATION_FAILURE',
  CANCEL_PRAYING_RESERVATION_CANCEL = '@@user/CANCEL_PRAYING_RESERVATION_CANCEL',
}

export interface UserProfile {
  readonly firstName: string;
  readonly lastName: string;
  readonly phoneNumber: string;
}

export interface UserState {
  readonly token?: string;
  readonly profile?: UserProfile;
  readonly reservePrayingTime?: Date | null;
  readonly creatingUserProfileDate?: Date;
}
